version: '3'
services:
  db:
    build:
      context: ./db
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER_INSERT}
        - MYSQL_PASSWORD=${MYSQL_USER_INSERT_PASSWORD}
        - MYSQL_USER_SELECT=${MYSQL_USER_SELECT}
        - MYSQL_USER_SELECT_PASSWORD=${MYSQL_USER_SELECT_PASSWORD}
    restart: always
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  api:
    build:
      context: ./api
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER_INSERT=${MYSQL_USER_INSERT}
        - MYSQL_USER_INSERT_PASSWORD=${MYSQL_USER_INSERT_PASSWORD}
        - COD_API_EMAIL=${COD_API_EMAIL}
        - COD_API_PASSWORD=${COD_API_PASSWORD}
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: dockerize -wait tcp://db:3306 -timeout 2m -wait-retry-interval 2s bin/start
    depends_on:
      - db
    links:
      - db

volumes:
  data:

networks:
  default:
    external: false
